apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-service-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/los-demos/${APP_NAME}.git
    targetRevision: main
    path: charts/python-service-1
  destination:
    server: https://kubernetes.default.svc
    namespace: python-service-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true